@server_HostAddress = http://localhost:5049

GET {{server_HostAddress}}/carplate/
Accept: application/json

###

GET {{server_HostAddress}}/carplate/id
Accept: application/json

###

POST {{server_HostAddress}}/carplate/
Content-Type: application/json

{
    "plate": "plate"
}

###

PUT {{server_HostAddress}}/carplate/id
Content-Type: application/json

{
    "id": "id",
    "plate": "plate"
}

###

DELETE  {{server_HostAddress}}/carplate/id

###

GET {{server_HostAddress}}/user/
Accept: application/json

###

GET {{server_HostAddress}}/user/id
Accept: application/json

###

GET {{server_HostAddress}}/user/id/car-plates
Accept: application/json

###

POST {{server_HostAddress}}/user/
Content-Type: application/json

{
    "plate": "plate"
}

###

PUT {{server_HostAddress}}/user/id
Content-Type: application/json

{
    "id": "id",
    "firstName": "firstName",
    "lastName": "lastName",
    "carPlates": [],
    "plate": "plate"
}

###

DELETE  {{server_HostAddress}}/user/id

###